# Generated by Django 5.2.4 on 2025-07-29 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, help_text="Employee's phone number.", max_length=20, null=True)),
                ('role', models.CharField(choices=[('Owner', 'Owner'), ('Cashier', 'Cashier'), ('Stock Manager', 'Stock Manager')], default='Cashier', help_text='The role of the employee.', max_length=50)),
                ('date_joined', models.DateField(auto_now_add=True, help_text='Date when the employee joined.')),
                ('is_active_employee', models.BooleanField(default=True, help_text='Is this employee currently active?')),
                ('user', models.OneToOneField(help_text='The associated Django user account.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee Profile',
                'verbose_name_plural': 'Employee Profiles',
                'ordering': ['user__username'],
            },
        ),
    ]
