# Generated by Django 5.2.4 on 2025-07-30 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='role',
            field=models.CharField(choices=[('Owner', 'Owner'), ('Cashier', 'Cashier'), ('Stock Manager', 'Stock Manager'), ('real Manager', 'real Manager')], default='Cashier', help_text='The role of the employee.', max_length=50),
        ),
    ]
