# Generated by Django 5.2.4 on 2025-07-28 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the product category', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description for the category', null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the product', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the product', null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Selling price of the product', max_digits=10)),
                ('stock_quantity', models.IntegerField(default=0, help_text='Current quantity of product in stock')),
                ('reorder_level', models.IntegerField(default=10, help_text='Minimum stock quantity to trigger a reorder alert')),
                ('is_active', models.BooleanField(default=True, help_text='Is the product currently available for sale?')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the product was added')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last date and time when the product details were updated')),
                ('category', models.ForeignKey(blank=True, help_text='Category the product belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
