# Generated by Django 5.2.4 on 2025-07-28 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount of the sale', max_digits=10)),
                ('sale_date', models.DateTimeField(auto_now_add=True, help_text='Date and time when the sale occurred')),
                ('user', models.ForeignKey(blank=True, help_text='User who processed the sale', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sale_date'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='Quantity of the product sold')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price of the product at the time of sale', max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Subtotal for this item (quantity * unit_price)', max_digits=10)),
                ('product', models.ForeignKey(help_text='The product sold', on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
                ('sale', models.ForeignKey(help_text='The sale this item belongs to', on_delete=django.db.models.deletion.CASCADE, to='inventory.sale')),
            ],
            options={
                'unique_together': {('sale', 'product')},
            },
        ),
    ]
