# Generated by Django 5.2.4 on 2025-07-30 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_sale_saleitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the supplier company', max_length=200, unique=True)),
                ('contact_person', models.CharField(blank=True, help_text='Main contact person at the supplier', max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, help_text="Supplier's phone number", max_length=20, null=True)),
                ('email', models.EmailField(blank=True, help_text="Supplier's email address", max_length=254, null=True)),
                ('address', models.TextField(blank=True, help_text="Supplier's physical address", null=True)),
                ('notes', models.TextField(blank=True, help_text='Any additional notes about the supplier', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(auto_now_add=True, help_text='Date the purchase order was created')),
                ('expected_delivery_date', models.DateField(blank=True, help_text='Expected date of delivery', null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount of the purchase order', max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Ordered', 'Ordered'), ('Received', 'Received'), ('Canceled', 'Canceled')], default='Pending', help_text='Current status of the purchase order', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about the purchase order', null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created the purchase order', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(help_text='The supplier for this purchase order', on_delete=django.db.models.deletion.PROTECT, to='inventory.supplier')),
            ],
            options={
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='Quantity of the product ordered')),
                ('unit_cost', models.DecimalField(decimal_places=2, help_text='Cost per unit from the supplier', max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Subtotal for this item (quantity * unit_cost)', max_digits=10)),
                ('product', models.ForeignKey(help_text='The product being ordered', on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
                ('purchase_order', models.ForeignKey(help_text='The purchase order this item belongs to', on_delete=django.db.models.deletion.CASCADE, to='inventory.purchaseorder')),
            ],
            options={
                'unique_together': {('purchase_order', 'product')},
            },
        ),
    ]
