# Generated by Django 5.2.4 on 2025-07-30 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_supplier_purchaseorder_purchaseorderitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_change', models.IntegerField(help_text='The amount by which stock changed (positive for increase, negative for decrease)')),
                ('adjustment_date', models.DateTimeField(auto_now_add=True, help_text='Date and time of the adjustment')),
                ('adjustment_type', models.CharField(choices=[('Add', 'Addition (e.g., found inventory)'), ('Remove', 'Removal (e.g., damaged, lost, spoilage)'), ('Return', 'Customer Return'), ('Physical Count', 'Adjustment after physical count'), ('Other', 'Other (specify in notes)')], default='Other', help_text='Type of stock adjustment', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Reason or additional details for the adjustment', null=True)),
                ('adjusted_by', models.ForeignKey(blank=True, help_text='User who made the adjustment', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(help_text='The product whose stock is being adjusted', on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
            ],
            options={
                'verbose_name_plural': 'Stock Adjustments',
                'ordering': ['-adjustment_date'],
            },
        ),
    ]
