# Generated by Django 5.2.4 on 2025-07-30 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_stockadjustment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="Customer's first name", max_length=100)),
                ('last_name', models.CharField(blank=True, help_text="Customer's last name", max_length=100, null=True)),
                ('email', models.EmailField(blank=True, help_text="Customer's email address (optional, but recommended)", max_length=254, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, help_text="Customer's phone number", max_length=20, null=True)),
                ('address', models.TextField(blank=True, help_text="Customer's physical address", null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, help_text='Date when the customer was added')),
                ('last_purchase', models.DateTimeField(blank=True, help_text="Date of customer's last purchase", null=True)),
                ('notes', models.TextField(blank=True, help_text='Any additional notes about the customer', null=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='The customer for this sale (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.customer'),
        ),
    ]
