# Generated by Django 5.2.4 on 2025-07-30 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_customer_sale_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, help_text='Unique barcode for the product', max_length=100, null=True, unique=True),
        ),
    ]
