# Generated by Django 5.2.5 on 2025-08-11 07:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Optional image for the product', max_length=255, null=True, verbose_name='image'),
        ),
    ]
