# Generated by Django 5.2.5 on 2025-08-11 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image for the product', null=True, upload_to='products/'),
        ),
    ]
